version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: your_db_user
      DATABASE_PASSWORD: your_db_password
      DATABASE_NAME: your_db_name
      TZ: America/Bogota
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
      TZ: America/Bogota
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
